#+ summary: Return the query to a resource by the resource_iri
CONSTRUCT {
?_resource_iri ?predicate ?prop .
?prop a ?type
}
WHERE {

?_resource_iri ?predicate ?prop 
{
?item ?predicate ?prop
}
OPTIONAL {
?prop a ?type
}
}
