#+ summary: Given a rdf type, returns all the resources related to the type
CONSTRUCT {
    ?item ?predicate ?prop .
    ?prop a ?type
}
WHERE {
    {
        SELECT DISTINCT ?item where {
            ?item a ?_type_iri .
        }
        LIMIT 100
        OFFSET 0
    }
    ?item ?predicate ?prop
    OPTIONAL {
        ?prop a ?type
    }
}