#+ summary: Given a rdf type, returns all the resources related to a list of property {rdfs:label}
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
    ?item ?predicate ?prop .
    ?prop a ?type
}
WHERE {
    {
        SELECT DISTINCT ?item where {
            ?item a ?_type_iri .
            ?item ?prop ?desc .
            VALUES ?prop { rdfs:label }
            filter regex(str(?desc),?_text,"i")
        }
    }
    ?item ?predicate ?prop
    OPTIONAL {
        ?prop a ?type
    }
}