#+ summary: Return the query to a resource by the resource_iri
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
CONSTRUCT {
    ?_resource_iri ?predicate ?prop .
    ?prop a ?type .
    ?prop rdfs:label ?label
}
WHERE {
    GRAPH ?_g_iri {
        ?_resource_iri ?predicate ?prop
        OPTIONAL {
            ?prop  a ?type
            OPTIONAL {
                ?prop rdfs:label ?label
            }
        }
    }
}