#+ summary: Given a rdf type, returns all the resources related to the type
PREFIX sd: <https://w3id.org/okn/o/sd#>
PREFIX sdm: <https://w3id.org/okn/o/sdm#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>



CONSTRUCT {
    ?model ?predicate ?prop .
    ?prop a ?type
}
WHERE {
    GRAPH ?_g_iri {
        {
            SELECT DISTINCT ?model where {
                ?model a ?type.
                ?model sdm:usefulForCalculatingIndex ?index .
                ?index rdfs:label ?indexLabel
                FILTER REGEX(?indexLabel, ?_label, "i")
                VALUES ?type {sdm:Model sdm:ModelConfiguration sdm:ModelConfigurationSetup}
            }
        }
        ?model ?predicate ?prop
        OPTIONAL {
         ?prop a ?type
        }
    }
}