#Name of the project
name: BusinessOntology

## OpenAPI Section
### Name, version and URL of the OpenAPI
### For more information about the section. Go to the official documentation
openapi:
  openapi: 3.0.1
  info:
    description: This is the API of the Business Ontology
    title: Business Ontology test
    version: v1
  externalDocs:
    description: busont
    url:  https://www.semanticarts.com/gist/previous-versions/
  servers:
    - url: http://localhost:8080/v1
      description: localhost server

## Ontologies
### List of ontologies
ontologies:
  - examples/business/ontology.xml

## SPARQL information
endpoint:
  url: http://localhost:7201/sparql
  prefix: https://businessontology.com/resource

## Filter the paths by methods
enable_get_paths: true
enable_post_paths: false
enable_delete_paths: false
enable_put_paths: false


follow_references: true
