#+ summary: Given a rdf type, returns all the resources related to the type
PREFIX sd: <https://w3id.org/okn/o/sd#>
PREFIX sdm: <https://w3id.org/okn/o/sdm#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


CONSTRUCT {
    ?model ?predicate ?prop .
    ?prop a ?type
}
WHERE {
    GRAPH ?_g_iri {
        {
            SELECT DISTINCT ?model where {
                ?model sd:hasVersion ?model_version .
                ?model_version sd:hasConfiguration ?model_c .
        		?model_c sd:hasSetup ?setup .
                ?setup sd:hasParameter ?param .
                ?param sdm:relevantForIntervention ?interv .
                ?interv a sdm:Intervention .
                ?interv rdfs:label ?intervLabel .
                FILTER REGEX(?intervLabel, ?_label, "i")
            }
        }
        ?model ?predicate ?prop
        OPTIONAL {
         ?prop a ?type
        }
    }
}