#+ summary: Given a rdf type, returns all the resources related to the type

PREFIX sd: <https://w3id.org/okn/o/sd#>
PREFIX sdm: <https://w3id.org/okn/o/sdm#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>


CONSTRUCT {
    ?setup ?predicate ?prop .
    ?prop a ?type .
    ?region ?region_p ?region_o .
    ?region_o ?sub_region_p ?sub_region_o .
}
WHERE {
        GRAPH ?_g_iri {
            {
                SELECT DISTINCT ?setup {
                  ?setup a sdm:ModelConfigurationSetup .
                  {
                    ?setup sd:hasOutput ?output.
                    ?output sd:hasPresentation ?vp.
                    ?vp sd:hasStandardVariable ?sv.
                  } UNION {
                    ?model sd:hasVersion ?version.
                    ?version sd:hasConfiguration ?configuration.
                    ?configuration sd:hasSetup ?setup .
                    ?model sdm:usefulForCalculatingIndex ?sv.
                  }
                  ?sv rdfs:label ?variableLabel .
                  FILTER REGEX(?variableLabel, ?_label, "i")
                }
            }
            {
                ?setup ?predicate ?prop
                OPTIONAL {
                 ?prop a ?type
                }
            }
            UNION {
                ?setup sdm:hasRegion ?region .
                ?region ?region_p ?region_o .
                FILTER (?region_p != <https://w3id.org/okn/o/sdm#geo>) .
                OPTIONAL {
                    ?region_o ?sub_region_p ?sub_region_o .
                    FILTER (?sub_region_p != <https://w3id.org/okn/o/sdm#geo>)
                }
            }
      }
}
