package edu.isi.oba.config;

public enum CONFIG_FLAG {
  ALWAYS_GENERATE_ARRAYS,
  DEFAULT_DESCRIPTIONS,
  DEFAULT_PROPERTIES,
  FOLLOW_REFERENCES,
  GENERATE_JSON_FILE,
  PATH_DELETE,
  PATH_GET,
  PATH_PATCH,
  PATH_POST,
  PATH_PUT,
  REQUIRED_PROPERTIES_FROM_CARDINALITY,
  USE_KEBAB_CASE_PATHS,
}
