package edu.isi.oba.config;

public enum CONFIG_FLAG {
  ALWAYS_GENERATE_ARRAYS,
  DEFAULT_DESCRIPTIONS,
  DEFAULT_PROPERTIES,
  FOLLOW_REFERENCES,
  PATH_DELETE,
  PATH_GET,
  PATH_PATCH,
  PATH_POST,
  PATH_PUT
}
